export const NEXT_PUBLIC_BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL!;
export const NEXT_PUBLIC_BACKEND_SPY_CATS = process.env.NEXT_PUBLIC_BACKEND_SPY_CATS!;
export const NEXT_PUBLIC_BACKEND_MISSIONS = process.env.NEXT_PUBLIC_BACKEND_MISSIONS;
